name: Deploy

on:
  push:
    paths:
      - '**.py'
      - "**.tsx"
      - "**.css"
      - "**.js"
      - '**.yml'
      - '**.html'
      - 'zappa_settings.json'
      - "**.json"
jobs:
  deploy_github_page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: list
        run: ls
        working-directory: ./webapp
      - name: Install dependencies
        run: yarn install
        working-directory: ./webapp
      - name: Build
        run: yarn build
        working-directory: ./webapp
        env:
          CI: false
          PUBLIC_URL: https://secyan.github.io/SECYAN-GEN/
          REACT_APP_URL: 'https://0.0.0.0:5000'
          GENERATE_SOURCEMAP: false

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./webapp/build